spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: admin@123.
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 20
      auto-commit: true
      pool-name: platformHikariCp
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select now()


  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        enabled: true
        min-idle: 1
        max-idle: 8
mybatis-plus:
  config-locations: classpath:xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
app:
  jwt:
    expire: 1  #minutes



