spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: admin@123.
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 20
      auto-commit: true
      pool-name: platformHikariCp
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select now()







  redis:
    database: 1
    host: localhost
    port: 6379
    jedis:
      pool:
        enabled: true
        min-idle: 1
        max-idle: 8
  data:
    mongodb:
      authentication-database: admin
      host: 192.168.10.73
      port: 27017
      password: admin@123.
      username: root
      database: platform



mybatis-plus:
  config-locations: classpath:com.francis.platform.mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
app:
  jwt:
    expire: 30  #minutes


ip:
  local-parsing: true
